---

- name: "Set up Cloudflare DNS records"
  hosts: localhost
  connection: local
  vars:
    dns_record_list:
      - domain: "cweagans.net"
        entries:
        - record: "mustang"
          value: "172.82.138.58"
          type: A
        - record: "cweagans.net"
          value: "66.111.4.53"
          type: A
        - record: "cweagans.net"
          value: "66.111.4.54"
          type: A
        - record: "www.cweagans.net"
          value: "mustang.cweagans.net"
          type: CNAME
        - record: "app01.atl"
          value: "mustang.cweagans.net"
          type: CNAME
        - record: "dokku"
          value: "mustang.cweagans.net"
          type: CNAME
        - record: "*.dokku"
          value: "mustang.cweagans.net"
          type: CNAME
        - record: "project"
          value: "mustang.cweagans.net"
          type: CNAME
        - record: "mail"
          value: "66.111.4.147"
          type: A
        - record: "cweagans.net"
          value: "keybase-site-verification=e7eXdPU3dQQVgI52BLawde8mpxK-gHeANtRQbhrA5qA"
          type: TXT
        - record: "mesmtp._domainkey.cweagans.net"
          value: "v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDmU1zu1Dxn/TVbPy7/n+suLFu4N7KUxv5O8wpPapGnXGEiwKW2zrXd51PBj1oWfuFG1E2cZoyk7bJQQJen8keSXOI1dbTAMNmflyD4fwLtU0IDr5vgHVjdsr0H5r2k3z/hWPdYBY4amqxnHx17cHYqyL+prmE8Ks1X5BddIi3a/QIDAQAB"
          type: TXT
        - record: "_adsp._domainkey.cweagans.net"
          value: "dkim=unknown"
          type: TXT
        - record: "cweagans.net"
          value: "v=spf1 include:spf.messagingengine.com ?all"
          type: TXT
        - record: "cweagans.net"
          value: "in1-smtp.messagingengine.com"
          priority: 10
          type: MX
        - record: "cweagans.net"
          value: "in2-smtp.messagingengine.com"
          priority: 20
          type: MX
      - domain: "cameronandalli.wedding"
        entries:
        - record: "@"
          value: "mustang.cweagans.net"
          type: CNAME
        - record: "www"
          value: "mustang.cweagans.net"
          type: CNAME
        - record: "staging"
          value: "mustang.cweagans.net"
          type: CNAME
      # Note: Cloudflare is configured with page rules to redirect to the .wedding
      # site for now.
      - domain: "cameronandalli.com"
        entries:
        - record: "@"
          value: "mustang.cweagans.net"
          type: CNAME
        - record: "www"
          value: "mustang.cweagans.net"
          type: CNAME

  tasks:
    - name: Set up Cloudflare DNS records
      cloudflare_dns:
        account_email: "me@cweagans.net"
        account_api_token: "{{ lookup('env', 'CLOUDFLARE_API_KEY') | default(omit) }}"
        domain: "{{ item.domain }}"
        type: "{{ item.type }}"
        record: "{{ item.record }}"
        value: "{{ item.value }}"
        state: "{{ item.state }}"
        port: "{{ item.port | default(omit)}}"
        priority: "{{ item.priority | default(omit) }}"
        proto: "{{ item.proto | default(omit) }}"
        service: "{{ item.service | default(omit) }}"
        ttl: "{{ item.ttl | default(omit) }}"
        weight: "{{ item.weight | default(omit) }}"
      with_dns_records: "{{ dns_record_list }}"
