---

- name: "Apply all common configuration"
  hosts: all
  roles:
    - common
    - user_accounts

- name: "Configure workstations"
  hosts: workstations
  roles:
    - desktop

- name: "Configure router"
  hosts: routers
  roles:
    - openwrt_router

- name: "Configure all servers"
  hosts: servers
  roles:
    - geerlingguy.security

- name: "Configure Dokku hosts"
  hosts: dokku
  roles:
    - angstwad.docker_ubuntu
    - dokku
