---

- name: "Apply all common configuration"
  hosts: all
  roles:
    - common
    - user_accounts

- name: "Configure workstations"
  hosts: workstations
  roles:
    - desktop

- name: "Configure all servers"
  hosts: servers
  roles:
    - geerlingguy.security

- name: "Configure Dokku hosts"
  hosts: dokku
  roles:
    - docker
    - dokku
