---

- name: "Apply all common configuration"
  hosts: all
  roles:
    - common

- name: "Configure workstations"
  hosts: workstations
  roles:
    - angstwad.docker_ubuntu
    - ubuntu_desktop

- name: "Configure all servers"
  hosts: servers
  roles:
    - user_accounts
    - geerlingguy.security

- name: "Configure Dokku hosts"
  hosts: dokku
  roles:
    - angstwad.docker_ubuntu
    - dokku
