---

- name: "Apply all common configuration"
  hosts: all
  roles:
    - common

- name: "Configure workstations"
  hosts: workstations
  roles:
    - desktop

- name: "Configure servers"
  hosts: servers
  roles:
    - geerlingguy.security
