---

- name: "Add the Dokku repo key"
  apt_key:
    id: C2E73424D59097AB
    url: https://packagecloud.io/gpg.key
    state: present

- name: "Add the Dokku packagecloud.io repo"
  apt_repository:
    repo: "deb https://packagecloud.io/dokku/dokku/ubuntu/ trusty main"
    state: present
    filename: "dokku"
    update_cache: yes

- name: "Set dokku debconf options"
  debconf:
    name: "dokku"
    setting: "{{ item.setting }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items: "{{ dokku_debconf_settings }}"

- name: "Install Dokku"
  apt:
    name: dokku
    state: present
  register: dokku_result

- name: "Install Dokku dependencies"
  shell: "dokku plugin:install-dependencies --core"
  when: dokku_result.changed

- name: "Download Dokku plugins"
  git:
    repo: "{{ item.repo }}"
    dest: "/var/lib/dokku/plugins/available/{{ item.name }}"
    version: "{{ item.version | default('master') }}"
  with_items: "{{ dokku_plugins }}"

- name: "Enable Dokku plugins"
  file:
    src: "/var/lib/dokku/plguins/available/{{ item.name }}"
    dest: "/var/lib/dokku/plugins/enabled/{{ item.name }}"
    state: link
  with_items: "{{ dokku_plugins }}"
  register: "dokku_plugin_enable_results"

- name: "Install Dokku plugin dependencies"
  shell: "dokku plugin:install-dependencies"
  when: dokku_plugin_enable_results.changed

- name: "Run install script for each newly enabled plugin"
  shell: "[ -e /var/lib/dokku/plugins/enabled/{{ item.item.name }}/install ] && /var/lib/dokku/plugins/enabled/{{ item.item.name }}/install"
  with_items: dokku_plugin_enable_results.results
