---

- name: "Set root password"
  user:
    name: root
    uid: 0
    state: present
    password: "{{ root_pass }}"

- name: "Ensure users exist"
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    state: present
    home: "/Users/{{ item.name }}"
    createhome: yes
    shell: "/usr/local/bin/{{ item.shell }}"
  with_items: user_accounts

- name: "Add authorized keys"
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_public_key }}"
    state: present
  with_items: user_accounts
