---

- name: "Set root password"
  user:
    name: root
    uid: 0
    state: present
    password: "{{ root_pass }}"

- name: "Ensure users exist"
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    state: present
    home: "/home/{{ item.name }}"
    createhome: yes
    password: "{{ item.pass }}"
    update_password: "always"
    groups: "{{ item.groups }}"
    append: yes
    shell: "/bin/{{ item.shell }}"
  with_items: "{{ user_accounts }}"

- name: "Add authorized keys"
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_public_key }}"
    state: present
  with_items: "{{ user_accounts }}"
