---

- name: "Install dependencies"
  apt:
    name: "{{ item }}"
    state: installed
  with_items: "{{ intellij_dependencies }}"

- name: Ensure /opt/intellij exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ intellij_path }}"
    - "{{ intellij_path }}/downloads"
    - "{{ intellij_path }}/{{ intellij_version }}"

- name: Download IntelliJ
  get_url:
    url: "{{ intellij_download_url }}"
    dest: "{{ intellij_path }}/downloads/{{ intellij_version }}.tar.gz"
  register: intellij_download

- name: Unpack IntelliJ
  unarchive:
    remote_src: yes
    src: "{{ intellij_path }}/downloads/{{ intellij_version }}.tar.gz"
    dest: "{{ intellij_path }}"
  when: intellij_download.changed

- name: Create 'latest' symlink
  file:
    src: "{{ intellij_path }}/{{ intellij_version }}"
    dest: "{{ intellij_path }}/latest"
    state: link

- name: Create bin symlink
  file:
    follow: yes
    src: "{{ intellij_path }}/latest/bin/idea.sh"
    dest: "/usr/bin/idea"
    state: link

- name: Create desktop entry
  copy:
    src: intellij.desktop
    dest: /usr/share/applications/intellij.desktop
    mode: 755
