---
galaxy_info:
  author: Natalio Ruiz
  description: Install Java SDK
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: Ubuntu
  versions:
    - xenial
  galaxy_tags:
    - system

dependencies: []