---

# Mac configuration
darwin_homebrew_taps:
  - argon/mas
  - caskroom/cask
  - caskroom/fonts
  - homebrew/completions
  - homebrew/dupes
  - homebrew/php
  - homebrew/versions
  - homebrew/x11
darwin_homebrew_packages:
  - ansible
  - bash
  - gist
  - git
  - git-flow
  - hub
  - trash
  - unrar
  - wget
  - xz
  - zsh
  - zsh-completions
  - zsh-history-substring-search
darwin_homebrew_casks:
  - alfred
  - bartender
  - dropbox
  - flux
  - font-inconsolata
  - google-chrome-beta
  - chrome-remote-desktop-host
  - slack
  - spotify
  - steam
  - steelseries-engine
  - transmission
  - vlc
homebrew_become_user: "cweagans"

# Debian configuration
debian_apt_repos:
  - "ppa:ansible/ansible"
  - "deb http://repository.spotify.com stable non-free"
  - "deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main"
  - "deb http://linux.dropbox.com/ubuntu/ xenial main"
  - "deb [arch=amd64,i386] http://repo.steampowered.com/steam/ precise steam"
  - "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
debian_apt_keys:
  # Spotify
  - keyserver: keyserver.ubuntu.com
    id: BBEBDCB318AD50EC6865090613B00F1FD2C19886
  # Slack
  - url: https://packagecloud.io/slacktechnologies/slack/gpgkey
    id: C2E73424D59097AB
  # Dropbox
  - keyserver: pgp.mit.edu
    id: 5044912E
  # Steam
  # - keyserver: keyserver.ubuntu.com
    # id: F24AEA9FB05498B7
  # Google
  - url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    id: 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991
debian_packages:
  - "dropbox"
  - "fonts-inconsolata"
  - "google-chrome-beta"
  - "redshift"
  - "slack-desktop"
  - "spotify-client"
  # - "steam"
  - "transmission"
  - "vlc"
