---

- name: "Ensure opkg packages are installed properly"
  opkg:
    name: "{{ item }}"
    state: present
  with_items: "{{ openwrt_router_packages }}"

- name: "Ensure that Ansible is installed/updated"
  pip:
    name: ansible
    state: latest

- name: "Generate system configuration files"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: "etc/config/system.j2", dest: "/etc/config/system" }
