---

- name: "Apply configuration regularly"
  cron:
    name: "run ansible playbook"
    minute: "{{ ansible_cron_minutes }}"
    state: present
    value: "/opt/ansible/configuration/scripts/refresh-configuration.sh"

- name: "Install zsh"
  apt:
    name: zsh
    state: latest

- name: "Apply sysctl configuration"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ common_sysctl }}"
