---

- name: "Install prerequisites"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates

- name: "Import Docker repo key"
  apt_key:
    keyserver: "p80.pool.sks-keyservers.net"
    id: "58118E89F3A912897C070ADBF76221572C52609D"
    state: present

- name: "Add apt repos and update cache if needed"
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-xenial main"
    state: present
  update_cache: yes

- name: "Ensure old lxc-docker package is not installed"
  apt:
    name: "lxc-docker"
    state: absent
    purge: yes

- name: "Install Docker"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "linux-image-extra-virtual"
    - "docker-engine"

- name: "Ensure Docker is running and starts on boot"
  systemd:
    name: docker
    enabled: yes
    state: started
