---

# This is done separately from other packages because Slack installation requires
# apt-transport-https to be available at install time.
- name: "Install Apt HTTPS transport"
  apt:
    name: "apt-transport-https"
    state: present
    update_cache: yes

- name: "Import repo keys"
  apt_key:
    keyserver: "{{ item.keyserver | default(omit) }}"
    id: "{{ item.id }}"
    url: "{{ item.url | default(omit) }}"
    state: present
  with_items: "{{ debian_apt_keys }}"

- name: "Add apt repos and update cache if needed"
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ debian_apt_repos }}"

- name: "Install packages"
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ debian_packages }}"

# Despite having a .deb available, Chrome RDH is not in the apt repo for some reason :(
- name: "Install Chrome Remote Desktop Host"
  include: debian-chrome-remote-desktop.yml
